### ISSUE TITLE
please add restart function

### ISSUE THREAD

**Issue by compact21** [cmaion/huawei_router#2]
I just downloaded your script

and I find it wonderful

could you add router reboot function

you see:
https://superuser.com/questions/1796071/how-to-reboot-my-modem-using-a-cli-command
https://superuser.com/questions/1794557/curl-reboot-huawei-b525

**Comment by compact21** [comment]
if it can be useful this is the script that is generated with the selenium IDE application

https://github.com/SeleniumHQ/selenium-ide


`
{
  "id": "9f56cf72-bbe5-45cc-b01c-f4e386bb0da8",
  "version": "2.0",
  "name": "router_reboot",
  "url": "https://192.168.1.1",
  "tests": [{
    "id": "44ea256c-08dd-4038-a9f7-9358fea9bed6",
    "name": "1",
    "commands": [{
      "id": "fe689f22-da0e-4d44-9645-fd18fad81e3d",
      "comment": "",
      "command": "open",
      "target": "/html/home.html",
      "targets": [],
      "value": ""
    }, {
      "id": "447d2516-c991-4917-a58b-a4a98998ccb0",
      "comment": "",
      "command": "setWindowSize",
      "target": "1280x959",
      "targets": [],
      "value": ""
    }, {
      "id": "bfccdfe4-f9ed-4d63-81e9-dbb2741b0c98",
      "comment": "",
      "command": "click",
      "target": "id=logout_span",
      "targets": [
        ["id=logout_span", "id"],
        ["css=#logout_span", "css:finder"],
        ["xpath=//span[@id='logout_span']", "xpath:attributes"],
        ["xpath=//div[@id='header_turnbg']/div/div[3]/div[2]/span/span", "xpath:idRelative"],
        ["xpath=//div[2]/span/span", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "0aed284c-3a67-422a-87bd-501aa46f30c9",
      "comment": "",
      "command": "type",
      "target": "id=password",
      "targets": [
        ["id=password", "id"],
        ["css=#password", "css:finder"],
        ["xpath=//input[@id='password']", "xpath:attributes"],
        ["xpath=//div[@id='login_password_wrapper']/span/input", "xpath:idRelative"],
        ["xpath=//div[3]/span/input", "xpath:position"]
      ],
      "value": "mypassword"
    }, {
      "id": "5343b650-da62-4890-b81d-ddf20c6bc07d",
      "comment": "",
      "command": "click",
      "target": "id=username",
      "targets": [
        ["id=username", "id"],
        ["css=#username", "css:finder"],
        ["xpath=//input[@id='username']", "xpath:attributes"],
        ["xpath=//div[@id='username_wrapper']/span/input", "xpath:idRelative"],
        ["xpath=//input", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "7cc3db53-9334-4859-93d4-f8181dbf8cba",
      "comment": "",
      "command": "type",
      "target": "id=username",
      "targets": [
        ["id=username", "id"],
        ["css=#username", "css:finder"],
        ["xpath=//input[@id='username']", "xpath:attributes"],
        ["xpath=//div[@id='username_wrapper']/span/input", "xpath:idRelative"],
        ["xpath=//input", "xpath:position"]
      ],
      "value": "admin"
    }, {
      "id": "de502e5e-acad-46fa-bc07-c79ee89bbced",
      "comment": "",
      "command": "click",
      "target": "id=password",
      "targets": [
        ["id=password", "id"],
        ["css=#password", "css:finder"],
        ["xpath=//input[@id='password']", "xpath:attributes"],
        ["xpath=//div[@id='login_password_wrapper']/span/input", "xpath:idRelative"],
        ["xpath=//div[3]/span/input", "xpath:position"]
      ],
      "value": "mypassword"
    }, {
      "id": "fa06b99b-3cac-40bd-aa8e-ce8d3d6e7036",
      "comment": "",
      "command": "click",
      "target": "id=pop_login",
      "targets": [
        ["id=pop_login", "id"],
        ["css=#pop_login", "css:finder"],
        ["xpath=//input[@id='pop_login']", "xpath:attributes"],
        ["xpath=//div[@id='dialog']/div/div[3]/span/input", "xpath:idRelative"],
        ["xpath=//div[3]/div/div[3]/span/input", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "0bff3457-f93b-4aa7-b21e-49c4873c6f5d",
      "comment": "",
      "command": "click",
      "target": "css=#settings > span",
      "targets": [
        ["css=#settings > span", "css:finder"],
        ["xpath=//a[@id='settings']/span", "xpath:idRelative"],
        ["xpath=//li[5]/a/span", "xpath:position"],
        ["xpath=//span[contains(.,'Impostazioni')]", "xpath:innerText"]
      ],
      "value": ""
    }, {
      "id": "913a0498-5e9e-42a7-b4d5-c4be6b8d58a7",
      "comment": "",
      "command": "mouseOver",
      "target": "css=#settings > span",
      "targets": [
        ["css=#settings > span", "css:finder"],
        ["xpath=//a[@id='settings']/span", "xpath:idRelative"],
        ["xpath=//li[5]/a/span", "xpath:position"],
        ["xpath=//span[contains(.,'Impostazioni')]", "xpath:innerText"]
      ],
      "value": ""
    }, {
      "id": "6a0a5f64-6376-499a-a713-12abfa3a2df3",
      "comment": "",
      "command": "mouseOut",
      "target": "css=#settings > span",
      "targets": [
        ["css=#settings > span", "css:finder"],
        ["xpath=//a[@id='settings']/span", "xpath:idRelative"],
        ["xpath=//li[5]/a/span", "xpath:position"],
        ["xpath=//span[contains(.,'Impostazioni')]", "xpath:innerText"]
      ],
      "value": ""
    }, {
      "id": "2f200bc4-5742-4e75-9001-92a4ffb0e01b",
      "comment": "",
      "command": "click",
      "target": "id=label_security",
      "targets": [
        ["id=label_security", "id"],
        ["css=#label_security", "css:finder"],
        ["xpath=//span[@id='label_security']", "xpath:attributes"],
        ["xpath=//li[@id='security']/span", "xpath:idRelative"],
        ["xpath=//li[8]/span", "xpath:position"],
        ["xpath=//span[contains(.,'Sicurezza')]", "xpath:innerText"]
      ],
      "value": ""
    }, {
      "id": "d3b9efdf-6fd6-4f31-919d-fb00008cd6b8",
      "comment": "",
      "command": "click",
      "target": "id=label_security",
      "targets": [
        ["id=label_security", "id"],
        ["css=#label_security", "css:finder"],
        ["xpath=//span[@id='label_security']", "xpath:attributes"],
        ["xpath=//li[@id='security']/span", "xpath:idRelative"],
        ["xpath=//li[8]/span", "xpath:position"],
        ["xpath=//span[contains(.,'Sicurezza')]", "xpath:innerText"]
      ],
      "value": ""
    }, {
      "id": "073c1866-e160-423f-9624-12721652df49",
      "comment": "",
      "command": "click",
      "target": "id=system",
      "targets": [
        ["id=system", "id"],
        ["css=#system", "css:finder"],
        ["xpath=//li[@id='system']", "xpath:attributes"],
        ["xpath=//ul[@id='menu_detail_list']/li[9]", "xpath:idRelative"],
        ["xpath=//div[2]/div/div/ul/li[9]", "xpath:position"],
        ["xpath=//li[contains(.,'Sistema')]", "xpath:innerText"]
      ],
      "value": ""
    }, {
      "id": "8f6bcf04-2b18-49e8-8b3e-e5d3b03d7ba9",
      "comment": "",
      "command": "click",
      "target": "id=label_reboot",
      "targets": [
        ["id=label_reboot", "id"],
        ["css=#label_reboot", "css:finder"],
        ["xpath=//span[@id='label_reboot']", "xpath:attributes"],
        ["xpath=//li[@id='reboot']/a/span", "xpath:idRelative"],
        ["xpath=//li[9]/ul/li[5]/a/span", "xpath:position"],
        ["xpath=//span[contains(.,'Riavvia')]", "xpath:innerText"]
      ],
      "value": ""
    }, {
      "id": "0bb6bd2a-b79d-4890-a832-280c33264dfb",
      "comment": "",
      "command": "mouseOver",
      "target": "id=label_reboot",
      "targets": [
        ["id=label_reboot", "id"],
        ["css=#label_reboot", "css:finder"],
        ["xpath=//span[@id='label_reboot']", "xpath:attributes"],
        ["xpath=//li[@id='reboot']/a/span", "xpath:idRelative"],
        ["xpath=//li[9]/ul/li[5]/a/span", "xpath:position"],
        ["xpath=//span[contains(.,'Riavvia')]", "xpath:innerText"]
      ],
      "value": ""
    }, {
      "id": "45874d3a-d06b-4a8d-85d3-f5565fd5d723",
      "comment": "",
      "command": "mouseOut",
      "target": "id=label_reboot",
      "targets": [
        ["id=label_reboot", "id"],
        ["css=#label_reboot", "css:finder"],
        ["xpath=//span[@id='label_reboot']", "xpath:attributes"],
        ["xpath=//li[@id='reboot']/a/span", "xpath:idRelative"],
        ["xpath=//li[9]/ul/li[5]/a/span", "xpath:position"],
        ["xpath=//span[contains(.,'Riavvia')]", "xpath:innerText"]
      ],
      "value": ""
    }, {
      "id": "d941b18e-94ba-4ab9-a165-71e51073cd73",
      "comment": "",
      "command": "click",
      "target": "id=reboot_apply_button",
      "targets": [
        ["id=reboot_apply_button", "id"],
        ["css=#reboot_apply_button", "css:finder"],
        ["xpath=//input[@id='reboot_apply_button']", "xpath:attributes"],
        ["xpath=//span[@id='span_reboot_apply_button']/input", "xpath:idRelative"],
        ["xpath=//input", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "ff67b87f-cadd-402c-a727-62095ae7b589",
      "comment": "",
      "command": "click",
      "target": "id=pop_confirm",
      "targets": [
        ["id=pop_confirm", "id"],
        ["css=#pop_confirm", "css:finder"],
        ["xpath=//input[@id='pop_confirm']", "xpath:attributes"],
        ["xpath=//input", "xpath:position"]
      ],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "d01dc067-de90-454a-a5fd-c640702e3017",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["44ea256c-08dd-4038-a9f7-9358fea9bed6"]
  }],
  "urls": ["https://192.168.1.1/"],
  "plugins": []
}
`

**Comment by cmaion** [comment]
Hi,

Great, thanks.
I've reworked a bit your commits and pushed 06f04b7e39db4a2b2093cab57c661bccd80e256d with your added features.

I have changed the way you switch between 3G/4G/auto: `huawei_router signal 3g`, `huawei_router signal 4g`,  `huawei_router signal auto`

**Comment by cmaion** [comment]
Closing

**Comment by compact21** [comment]
Thank you
